from Fibonacci import *
s = Solution()
print s.Fibonacci(1)
print s.Fibonacci(2)
print s.Fibonacci(3)
print s.Fibonacci(4)
print s.Fibonacci(5)
print s.Fibonacci(6)
print s.Fibonacci(7)
print s.Fibonacci(8)
print s.Fibonacci(9)
print s.Fibonacci(10)
print s.Fibonacci(11)
print s.Fibonacci(12)
print s.Fibonacci(13)
print s.Fibonacci(14)
print s.Fibonacci(15)
print s.Fibonacci(16)
print s.Fibonacci(39)